const currenturl = window.location.origin;
let endpoint;
if(currenturl === "https://shop.jagota.com") {
  endpoint = "https://magentoadmin.jagota.com/";
} else {
  endpoint = "https://jtbstaging.iksulalive.com/";
}

let erpendpoint;
if(currenturl === "https://shop.jagota.com") {
  erpendpoint = "https://nodeapi.jagota.com";
} else {
  erpendpoint = "https://nodeapi-staging.jagota.com";
}

const URL = {
  BaseURL: `${endpoint}rest/V1`,
  ERP_URL: erpendpoint
  // ERP_URL: `https://nodeapi.jagota.com`
  // ERP_URL: `https://nodeapi-staging.jagota.com`
};

const request = {
  erplogin: `${URL?.ERP_URL}/login/b2b`,
  erprequest: `${URL?.ERP_URL}`,
  image: endpoint,
  adminLogin: `${URL.BaseURL}/integration/admin/token`,
  b2cRegister: `${URL.BaseURL}/customers/`,
  userLogin: `${URL.BaseURL}/jagota/customer/token`,
  userData: `${URL.BaseURL}/jagota/customers/me`,
  deletewishlist: `${URL.BaseURL}/jagota/removeWishlist`,
  addWishlist: `${URL.BaseURL}/jagota/addWishlist`,
  addFav: `${URL.BaseURL}/jagota/favouritesCreate`,
  recent: `${URL.BaseURL}/orders`,
  cardid: `${URL.BaseURL}/carts/mine`,
  cartadd: `${URL.BaseURL}/Jagota/addcart`,
  cartupdate: `${URL.BaseURL}/Jagota/itemUpdate`,
  carttotal: `${URL.BaseURL}/carts/mine/totals`,
  categorylist: `${URL.BaseURL}/categories`,
  shippingaddress: `${URL.BaseURL}/customers/me/shippingAddress`,
  billingaddress: `${URL.BaseURL}/customers/me/billingAddress`,
  deliverytimelist: `${URL.BaseURL}/jagota/getDeliveryTime`,
  createorder: `${URL.BaseURL}/jagota/orders`,
  brands: `${URL.BaseURL}/Jagota/createBrands`,
  mainslider: `${URL.BaseURL}/Jagota/createSlider`,
  promotionbanner: `${URL.BaseURL}/Jagota/createPromotionalslider`,
  recommendedbanner: `${URL.BaseURL}/Jagota/createRecommendedSliders`,
  catalogbanner: `${URL.BaseURL}/Jagota/createCatalogBanners`,
  parentcategory: `${URL.BaseURL}/jagota/getParentCategory`,
  bloglist: `${URL.BaseURL}/blogLists/`,
  countryfilter: `${URL.BaseURL}/jagota/getCountryList`,
  pricefilter: `${URL.BaseURL}/jagota/getPriceList`,
  nocompanyplplist: `${URL.BaseURL}/jagota/getProductsListFilter`,
  catalogheader: `${URL.BaseURL}/jagota/getCategoryType/2`,
  typeid: `${URL.BaseURL}/jagota/getCategoryType/7`,
  companylist: `${URL.BaseURL}/Jagota/getCompanyList/`,
  store: `${URL.BaseURL}/Jagota/getStoreList/`,
  createquotation: `${URL.BaseURL}/jagota/createQuotation`,
  newlog: `${URL.BaseURL}/jagota/customerActivityCreate/`,
  createnotification: `${URL.BaseURL}/jagota/notificationCreate/`,
  createbranch: `${URL.BaseURL}/jagota/createBranch`,
  updatebranch: `${URL.BaseURL}/jagota/updateBranch`,
  deletebranch: `${URL.BaseURL}/jagota/deleteBranch`,
  profileimage: `${URL.BaseURL}/Jagota/profile/`,
  customerstatus: `${URL.BaseURL}/Jagota/statusUpdate`,
  addnewuser: `${URL.BaseURL}/jagota/customer/create`,
  updateuser: `${URL.BaseURL}/jagota/customer/update`,
  ordersplitcreate: `${URL.BaseURL}/jagota/orderSplitCreate`,
  ordersplitupdate: `${URL.BaseURL}/jagota/orderSplitUpdate`,
  splitorderdelete: `${URL.BaseURL}/jagota/orderItemDelete`,
  deletecartitem: `${URL.BaseURL}/Jagota/cartDelete/`,
  productslider: `${URL.BaseURL}/Jagota/Productsliderlist`,
  fetchfav: `${URL.BaseURL}/jagota/getFavourites`,
  fetchrecent: `${URL.BaseURL}/jagota/recentOrder`,
  getbranch: `${URL.BaseURL}/jagota/customerIdBranch`,
  getAllBranch: `${URL.BaseURL}/jagota/customerAllBranch`,
  getCountry: `${URL.BaseURL}/jagota/getCountry`,
  getstate: `${URL.BaseURL}/jagota/getProvince`,
  getdistrict: `${URL.BaseURL}/jagota/getAmphur`,
  getsubdistrict: `${URL.BaseURL}/jagota/getTumbol`,
  updateprofile: `${URL.BaseURL}/awCaCompanyUser`,
  getactivitylogs: `${URL.BaseURL}/jagota/getCustomerActivity`,
  getcompanyusers: `${URL.BaseURL}/awCaCompanyUser/allForCompany`,
  getcompanyroles: `${URL.BaseURL}/Jagota/rolesByCompanyId`,
  getimagebyid: `${URL.BaseURL}/jagota/customer/profileById`,
  getcompanybranch: `${URL.BaseURL}/jagota/companyBranch`,
  deletefav: `${URL.BaseURL}/jagota/deleteFavourites`,
  clearcart: `${URL.BaseURL}/jagota/deleteCart`,
  deletefromcart: `${URL.BaseURL}/Jagota/cartDelete`,
  getordersplit: `${URL.BaseURL}/jagota/orderSplitGet`,
  getcatalogpdp: `${URL.BaseURL}/jagota/getProduct`,
  getrelatedproducts: `${URL.BaseURL}/Jagota/ReletedProducts`,
  getratingreview: `${URL.BaseURL}/Jagota/reviewlist`,
  thumbsupdown: `${URL.BaseURL}/Jagota/createHelpfulCount/`,
  catalogfilter: `${URL.BaseURL}/jagota/getCatalogProductsFilter`,
  getsubcategory: `${URL.BaseURL}/jagota/getSubCategory`,
  getcart: `${URL.BaseURL}/Jagota/cartList`,
  getwishlist: `${URL.BaseURL}/jagota/getWishlist?customerId=`,
  createreviewrating: `${URL.BaseURL}/Jagota/createProductReview/`,
  changepassword: `${URL.BaseURL}/jagota/resetPassword`,
  search: `${URL.BaseURL}/lof-autosearch/autosearch`,
  getnotification: `${URL.BaseURL}/jagota/getCustomerNotification`,
  readnotification: `${URL.BaseURL}/jagota/readStatusChange`,
  allroles: `${URL.BaseURL}/awCaRole`,
  addressbasedorder: `${URL.BaseURL}/jagota/orderBasedAddress`,
  selectedorder: `${URL.BaseURL}/jagota/orderDetail`,
  getproductpdp: `${URL.BaseURL}/jagota/getMyProduct`,
  productplp: `${URL.BaseURL}/jagota/getMyProducts`,
  productplpfilter: `${URL.BaseURL}/jagota/getMyProductsFilter`,
  orderslist: `${URL.BaseURL}/jagota/orderslist`,
  orderdetails: `${URL.BaseURL}/jagota/orderdetails`,
  creditcheck: `${URL?.BaseURL}/jagota/getCredit`,
  promoslider: `${URL?.BaseURL}/Jagota/createPromotionalslider`,
  paymenttype: `${URL?.BaseURL}/jagota/getCustomerType`,
  maintenance: `${URL?.BaseURL}/jagota/getMaintainanceCheck`,
  reorder: `${URL.BaseURL}/jagota/reorder`,
  searchpageapi: `${URL?.BaseURL}/jagota/getSearchResultFilter`,
  searchpagecategory: `${URL?.BaseURL}/jagota/getSearchResultFilterCategory`,
  catpricefilter: `${URL?.BaseURL}/jagota/getFilterPrice`,
  invoicelist: `${URL?.BaseURL}/jagota/complaints/invoicelists`,
  complaintproducts: `${URL?.BaseURL}/jagota/complaints/getproducts`,
  savecomplaint: `${URL?.BaseURL}/jagota/complaints/savecomplaints`,
  parentorderid: `${URL?.BaseURL}/Jagota/getUniqueId`,
  changelang: `${URL?.BaseURL}/jagota/updateCustomerStore`,
  recommendedslider: `${URL?.BaseURL}/Jagota/createRecommendedSliders`,
  erpcustomerinfo: `${URL?.ERP_URL}/finance/get-customer-info?`,
  erpcustomerbilling: `${URL?.ERP_URL}/finance/get-customer-billing?`,
  erpcustomerinvoice: `${URL?.ERP_URL}/finance/get-customer-invoice?`,
  erpcustomerinvoicedetail: `${URL?.ERP_URL}/finance/get-customer-invoice-detail?`,
  complaintcheck: `${URL?.BaseURL}/jagota/complaints/complaintCheck/?order_id=`,
  erppaymenthistory: `${URL?.ERP_URL}/finance/get-payment-history?`,
  quoteitemupdate: `${URL?.BaseURL}/Jagota/quoteItemUpdate`,
  catalogpricefilter: `${URL?.BaseURL}/jagota/getCatalogProductsFilterPrice`,
  myproductpricefilter: `${URL?.BaseURL}/jagota/getMyProductsFilterPrice`,
  catalogcountry: `${URL?.BaseURL}/jagota/getCatalogProductsFilterCountry`,
  productcountry: `${URL?.BaseURL}/jagota/getMyProductsFilterCountry`,
  searchcountry: `${URL?.BaseURL}/jagota/getFilterCountry`,
  productcathighlight: `${URL?.BaseURL}/jagota/getMyProductsFilterCategory`,
  erpgetcountry: `${URL?.ERP_URL}/branch/get-country?custCode=`,
  erpgetstate: `${URL?.ERP_URL}/branch/get-region?custCode=`,
  erpgetdistrict: `${URL?.ERP_URL}/branch/get-province?custCode=`,
  erpsubdistrict: `${URL?.ERP_URL}/branch/get-amphur`,
  erppincode: `${URL?.ERP_URL}/branch/get-tumbol`,
  promolist: `${URL?.BaseURL}/Jagota/getPromotion/`,
  promodetails: `${URL?.BaseURL}/Jagota/getPromotionDetails/`,
  promoclose: `${URL?.BaseURL}/Jagota/setPromotionStatus/`,
  getTerms: `${URL?.BaseURL}/Jagota/getTermsConditionStatus/`,
  setTerms: `${URL?.BaseURL}/Jagota/setTermsConditionStatus/`,
  getcookies: `${URL?.BaseURL}/Jagota/getCookiesStatus/`,
  setcookies: `${URL?.BaseURL}/Jagota/setCookiesStatus/`,
  getcookiescmsEnglish:`${URL?.BaseURL}/cmsPage/`,
  generalFIlter: `${URL?.BaseURL}/jagota/getSubCategoryFilterList`,
  brandFilterCategory: `${URL?.BaseURL}/jagota/getCatalogProductsFilterBrand/`,
  brandFilterMyProduct: `${URL?.BaseURL}/jagota/getMyProductsFilterBrand/`,
  brandFilterSearch: `${URL?.BaseURL}/jagota/getFilterBrand/`,
  productTypeMyProduct: `${URL?.BaseURL}/jagota/getMyProductsFilterProductType/`,
  productTypeCatalog: `${URL?.BaseURL}/jagota/getCatalogProductsFilterProductType/`,
  productTypeSearch: `${URL?.BaseURL}/jagota/getFilterProductType/`,
};

export default request;
